import Head from 'next/head'
import { Flex, Heading } from '@chakra-ui/react'
import { Logo } from '@/component/logo'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        as="main"
        minH="100vh"
        w="full"
        backgroundImage="https://i0.wp.com/www.3dart.it/wp-content/uploads/2020/06/PS5-teaser_Still005.jpg?resize=1536%2C864&ssl=1"
        backgroundSize="cover"
        p={2}
        direction="column"
      >
        <Logo />
        <Heading>Hello</Heading>
      </Flex>
    </>
  )
}
