version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-postgres}"
      POSTGRES_USER: "${POSTGRES_USER:-dbuser}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgrespassword}"
volumes:
  postgres:
    driver: local
